# Generated by Django 3.2 on 2025-08-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('lab_id', models.CharField(blank=True, max_length=50)),
                ('segment', models.CharField(blank=True, max_length=100)),
                ('ClinicalName', models.CharField(blank=True, max_length=50)),
                ('sales_person', models.CharField(blank=True, max_length=50)),
                ('sample_collector', models.CharField(blank=True, max_length=50)),
                ('refby', models.CharField(blank=True, max_length=100)),
                ('testdetails', models.JSONField(blank=True)),
                ('bill_no', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('total', models.CharField(blank=True, max_length=50)),
                ('discount', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.JSONField(blank=True)),
                ('MultiplePayment', models.JSONField(blank=True, max_length=150)),
                ('credit_amount', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('patientname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('age_type', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.JSONField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
