# Generated by Django 3.2 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251229_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
